name: Build Armbian Proxmox
on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

permissions:
    contents: write

jobs:
  build-proxmox:
    strategy:
      matrix:
        board: [orangepi5]
        branch: [legacy, edge]
        system: [bookworm]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install git -y
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Clone Armbian build repository
        run: |
          git clone --depth=1 --branch=main https://github.com/armbian/build
      - name: Build variants
        run: |
          MAIN_PARAMS="NO_APT_CACHER=no KERNEL_CONFIGURE=no BUILD_MINIMAL=yes BOARD=${{ matrix.board }} ENABLE_EXTENSIONS=install-proxmox-port"
          cp -R userpatches/ build/
          cd build
          ./compile.sh $MAIN_PARAMS BRANCH=${{ matrix.branch }} RELEASE=${{ matrix.system }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: "build/output/images/**"
          tag_name: orangepi3b-server-${{ steps.date.outputs.date }}
